#!/usr/bin/python

import configuration , ui

import sys


def main ( argv ) :

    # NOTE : Why not open db within the configuration reading ?
    config = configuration.FuelpadConfig( True )
    config.db.open( config )

    ui.FuelpadWindow( config )

    ui.main_loop()

    config.db.close()
    config.save()

if __name__ == "__main__" :
    main( sys.argv )

